# Necessary imports

In [23]:
import pandas as pd
from sklearn.preprocessing import StandardScaler



scaler = StandardScaler()

In [4]:
data = pd.read_csv('C:/Users\Morsi Store DZ/rain-prediction/rain-prediction-dataset/train.csv')
print(data.head())

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\Morsi Store DZ\AppData\Local\Temp\ipykernel_6956\1496207288.py:1: SyntaxWarning: invalid escape sequence '\M'
  data = pd.read_csv('C:/Users\Morsi Store DZ/rain-prediction/rain-prediction-dataset/train.csv')

   Day        Date            City  MinTemp  MaxTemp  Rainfall  Evaporation  \
0    0  2010-01-01         Algiers     19.4     31.9       5.0          NaN
1    1  2010-01-02           Setif     18.6     29.1      12.4          NaN
2    2  2010-01-03  Sidi Bel Abbes     12.2     29.7       0.0          NaN
3    3  2010-01-04          Skikda     14.8     32.8       0.0          NaN
4    4  2010-01-05          Skikda     15.0     35.8       0.0          NaN

   Sunshine WindGustDir  WindGustSpeed  ... Humidity9am Humidity3pm  \
0       NaN         NNE           39.0  ...        70.0        40.0
1       NaN           W           56.0  ...        88.0        48.0
2       NaN           W           30.0  ...        57.0        32.0
3       NaN          SW           30.0  ...        55.0        24.0
4       NaN           W           46.0  ...        46.0        13.0

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1012.2       1008.5       NaN       1.0     23.4     30.9        Yes
1       1007.8       1006.2       5.0       NaN     20.6     28.0        Yes
2       1014.4       1012.5       NaN       NaN     18.0     28.0         No
3       1017.5       1013.6       NaN       NaN     21.3     30.6         No
4       1014.9       1011.5       NaN       NaN     23.3     34.9         No

   RainTomorrow
0           Yes
1            No
2            No
3            No
4            No

[5 rows x 24 columns]

In [8]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76672 entries, 0 to 76671
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Day            76672 non-null  int64
 1   Date           76672 non-null  object
 2   City           76672 non-null  object
 3   MinTemp        76453 non-null  float64
 4   MaxTemp        76478 non-null  float64
 5   Rainfall       76672 non-null  float64
 6   Evaporation    46996 non-null  float64
 7   Sunshine       44312 non-null  float64
 8   WindGustDir    71517 non-null  object
 9   WindGustSpeed  71554 non-null  float64
 10  WindDir9am     70965 non-null  object
 11  WindDir3pm     75134 non-null  object
 12  WindSpeed9am   76081 non-null  float64
 13  WindSpeed3pm   75872 non-null  float64
 14  Humidity9am    75811 non-null  float64
 15  Humidity3pm    75834 non-null  float64
 16  Pressure9am    69106 non-null  float64
 17  Pressure3pm    69081 non-null  float64
 18  Cloud9am       48471 non-null  float64
 19  Cloud3pm       47717 non-null  float64
 20  Temp9am        76203 non-null  float64
 21  Temp3pm        76201 non-null  float64
 22  RainToday      76672 non-null  object
 23  RainTomorrow   76672 non-null  object
dtypes: float64(16), int64(1), object(7)
memory usage: 14.0+ MB
None

In [9]:
print(data.describe())

                Day       MinTemp       MaxTemp      Rainfall   Evaporation  \
count  76672.000000  76453.000000  76478.000000  76672.000000  46996.000000
mean   38335.500000     11.894520     22.833249      2.456764      5.223302
std    22133.444257      6.361629      6.845794      8.597603      4.025298
min        0.000000     -8.200000     -4.100000      0.000000      0.000000
25%    19167.750000      7.400000     17.800000      0.000000      2.575000
50%    38335.500000     11.700000     22.300000      0.000000      4.400000
75%    57503.250000     16.500000     27.600000      0.800000      7.000000
max    76671.000000     31.400000     48.100000    367.600000     82.400000

           Sunshine  WindGustSpeed  WindSpeed9am  WindSpeed3pm   Humidity9am  \
count  44312.000000   71554.000000  76081.000000  75872.000000  75811.000000
mean       7.564127      39.776421     13.860806     18.517806     69.327156
std        3.792560      13.530258      8.878743      8.832235     18.855473
min        0.000000       6.000000      0.000000      0.000000      0.000000
25%        4.800000      31.000000      7.000000     13.000000     57.000000
50%        8.400000      39.000000     13.000000     17.000000     70.000000
75%       10.600000      48.000000     19.000000     24.000000     84.000000
max       14.300000     135.000000     87.000000     83.000000    100.000000

        Humidity3pm   Pressure9am   Pressure3pm      Cloud9am      Cloud3pm  \
count  75834.000000  69106.000000  69081.000000  48471.000000  47717.000000
mean      52.264103   1017.746129   1015.384813      4.350209      4.458893
std       20.625299      7.057659      6.965096      2.866740      2.695716
min        0.000000    983.700000    981.400000      0.000000      0.000000
25%       38.000000   1013.100000   1010.700000      1.000000      2.000000
50%       53.000000   1017.700000   1015.300000      5.000000      5.000000
75%       66.000000   1022.500000   1020.100000      7.000000      7.000000
max      100.000000   1041.000000   1039.600000      9.000000      9.000000

            Temp9am       Temp3pm
count  76203.000000  76201.000000
mean      16.747223     21.349823
std        6.345111      6.684699
min       -5.500000     -4.400000
25%       12.200000     16.500000
50%       16.500000     20.800000
75%       21.200000     25.900000
max       40.200000     46.100000

In [10]:
missing_values = data.isnull().sum()
print(missing_values)

Day                  0
Date                 0
City                 0
MinTemp            219
MaxTemp            194
Rainfall             0
Evaporation      29676
Sunshine         32360
WindGustDir       5155
WindGustSpeed     5118
WindDir9am        5707
WindDir3pm        1538
WindSpeed9am       591
WindSpeed3pm       800
Humidity9am        861
Humidity3pm        838
Pressure9am       7566
Pressure3pm       7591
Cloud9am         28201
Cloud3pm         28955
Temp9am            469
Temp3pm            471
RainToday            0
RainTomorrow         0
dtype: int64

In [11]:
data.tail()

,Day,Date,City,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
76667,76667,2014-12-27,Annaba,26.1,34.3,0.0,5.0,9.0,NNW,33.0,...,77.0,65.0,1007.0,1004.9,7.0,8.0,28.6,32.2,No,No
76668,76668,2014-12-28,Algiers,26.9,33.6,0.0,5.4,3.9,NW,28.0,...,79.0,56.0,1008.3,1004.9,8.0,7.0,29.1,33.1,No,No
76669,76669,2014-12-29,Sidi Bel Abbes,26.2,33.5,0.0,6.2,3.7,W,28.0,...,77.0,74.0,1008.1,1005.0,7.0,8.0,29.1,30.2,No,Yes
76670,76670,2014-12-30,Skikda,24.8,33.3,3.2,3.6,5.1,N,33.0,...,93.0,54.0,1008.3,1004.8,7.0,7.0,25.5,32.7,Yes,Yes
76671,76671,2014-12-31,Setif,24.7,33.3,13.6,5.4,7.0,N,54.0,...,83.0,60.0,1008.0,1005.1,7.0,7.0,27.8,32.2,Yes,Yes

In [16]:
data['Date'] = pd.to_datetime(data['Date'])

# Convert categorical columns like 'RainToday', 'RainTomorrow' to binary (0/1) or categorical data types
data['RainToday'] = data['RainToday'].map({'Yes': 1, 'No': 0})
data['RainTomorrow'] = data['RainTomorrow'].map({'Yes': 1, 'No': 0})
print(data.info())
data = data.drop_duplicates()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76672 entries, 0 to 76671
Data columns (total 24 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Day            76672 non-null  int64
 1   Date           76672 non-null  datetime64[ns]
 2   City           76672 non-null  object
 3   MinTemp        76453 non-null  float64
 4   MaxTemp        76478 non-null  float64
 5   Rainfall       76672 non-null  float64
 6   Evaporation    46996 non-null  float64
 7   Sunshine       44312 non-null  float64
 8   WindGustDir    71517 non-null  object
 9   WindGustSpeed  71554 non-null  float64
 10  WindDir9am     70965 non-null  object
 11  WindDir3pm     75134 non-null  object
 12  WindSpeed9am   76081 non-null  float64
 13  WindSpeed3pm   75872 non-null  float64
 14  Humidity9am    75811 non-null  float64
 15  Humidity3pm    75834 non-null  float64
 16  Pressure9am    69106 non-null  float64
 17  Pressure3pm    69081 non-null  float64
 18  Cloud9am       48471 non-null  float64
 19  Cloud3pm       47717 non-null  float64
 20  Temp9am        76203 non-null  float64
 21  Temp3pm        76201 non-null  float64
 22  RainToday      0 non-null      float64
 23  RainTomorrow   0 non-null      float64
dtypes: datetime64[ns](1), float64(18), int64(1), object(4)
memory usage: 14.0+ MB
None

In [18]:
def classify_seasons(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

data['Month'] = data['Date'].dt.month
data['Season'] = data['Month'].apply(classify_seasons)

### Handling Outliers

In [19]:
Q1 = data['Rainfall'].quantile(0.25)
Q3 = data['Rainfall'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Remove outliers
data = data[(data['Rainfall'] >= lower_bound) & (data['Rainfall'] <= upper_bound)]

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 62522 entries, 2 to 76669
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Day            62522 non-null  int64
 1   Date           62522 non-null  datetime64[ns]
 2   City           62522 non-null  object
 3   MinTemp        62346 non-null  float64
 4   MaxTemp        62356 non-null  float64
 5   Rainfall       62522 non-null  float64
 6   Evaporation    38519 non-null  float64
 7   Sunshine       36092 non-null  float64
 8   WindGustDir    58485 non-null  object
 9   WindGustSpeed  58505 non-null  float64
 10  WindDir9am     57614 non-null  object
 11  WindDir3pm     61290 non-null  object
 12  WindSpeed9am   62041 non-null  float64
 13  WindSpeed3pm   61868 non-null  float64
 14  Humidity9am    61925 non-null  float64
 15  Humidity3pm    61912 non-null  float64
 16  Pressure9am    56326 non-null  float64
 17  Pressure3pm    56303 non-null  float64
 18  Cloud9am       39270 non-null  float64
 19  Cloud3pm       38606 non-null  float64
 20  Temp9am        62209 non-null  float64
 21  Temp3pm        62177 non-null  float64
 22  RainToday      0 non-null      float64
 23  RainTomorrow   0 non-null      float64
 24  Month          62522 non-null  int32
 25  Season         62522 non-null  object
dtypes: datetime64[ns](1), float64(18), int32(1), int64(1), object(5)
memory usage: 12.6+ MB

### Normalizing,Scaling Numeric Data

In [25]:
numerical_columns = ['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine', 'Humidity9am', 'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'WindSpeed9am', 'WindSpeed3pm']

# Scale numerical columns
data[numerical_columns] = scaler.fit_transform(data[numerical_columns])
data[numerical_columns]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,WindSpeed9am,WindSpeed3pm
2,0.084638,0.915255,-0.400405,NaN,NaN,-0.503966,-0.853023,-0.592734,-0.485305,-0.509958,0.092915
3,0.488529,1.369549,-0.400405,NaN,NaN,-0.611137,-1.258648,-0.136142,-0.323200,-0.279279,-1.062861
4,0.519598,1.809189,-0.400405,NaN,NaN,-1.093406,-1.816384,-0.519090,-0.632674,-1.086655,-0.138240
5,0.721544,1.516096,-0.400405,NaN,NaN,-0.932650,-2.120603,-0.636920,-0.632674,-1.317333,0.901958
6,0.519598,1.398859,-0.400405,NaN,NaN,-1.146992,-1.613571,-0.519090,-0.455831,-0.509958,NaN
...,...,...,...,...,...,...,...,...,...,...,...
76665,2.274972,1.545405,-0.400405,-0.277632,-0.308603,0.514157,0.515964,-1.505917,-1.723201,-0.048600,-0.831705
76666,2.383711,1.428168,1.634064,0.162081,-0.722012,-0.128868,0.414557,-1.756305,-1.752674,0.989454,0.092915
76667,2.243903,1.589369,-0.400405,-0.131061,0.242608,0.567743,0.820183,-1.682662,-1.605306,0.182079,0.670803
76668,2.368177,1.486786,-0.400405,-0.033347,-1.162981,0.674914,0.363854,-1.491188,-1.605306,-0.279279,0.092915
76669,2.259437,1.472132,-0.400405,0.162081,-1.218102,0.567743,1.276511,-1.520645,-1.590569,-0.279279,-0.369395